# Generated by Django 4.0.3 on 2022-03-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='discount', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(default='https: // www.google.com/')),
                ('short_title', models.TextField(unique=True)),
                ('long_title', models.TextField()),
                ('cost', models.FloatField(default=0)),
                ('mrp', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('desc', models.TextField()),
                ('discounts', models.TextField()),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(db_column='category', default='discount', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.category', to_field='category')),
                ('prod', models.ForeignKey(db_column='prod_name', default='', on_delete=django.db.models.deletion.CASCADE, to='home.products', to_field='short_title')),
            ],
        ),
    ]
