# Generated by Django 4.0.3 on 2022-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('password', models.TextField()),
                ('cpassword', models.TextField()),
            ],
        ),
    ]
