# Generated by Django 4.0.3 on 2022-03-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_users_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod', models.ForeignKey(db_column='prod_name', default='', on_delete=django.db.models.deletion.CASCADE, to='home.products', to_field='short_title')),
                ('uid', models.ForeignKey(db_column='user_id', default='', on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
