# Generated by Django 4.0.3 on 2022-04-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_users_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_payment_id', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_pid', models.ForeignKey(db_column='pid', default='', on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('user_id', models.ForeignKey(db_column='uid', default='', on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
    ]
