# Generated by Django 4.0.3 on 2022-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_orderitems_orderpayment_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
