# Generated by Django 4.0.3 on 2022-04-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_orderpayment_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='user_id',
            new_name='uid',
        ),
    ]
