# Generated by Django 4.0.3 on 2022-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_user_id_orderpayment_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
